config/routes.rb
Rails.application.routes.draw do
  resources :games do
    get :autocomplete_user_email, :on => :collection
  end
  resources :questions
  resources :games

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations'}

  get '/promote' => 'users#promote'
  post '/promote' => 'users#update'

  get 'show_review' => 'questions#show_review'
  get 'accept_review' => 'questions#accept_review'
  get 'show_game' => 'games#show'
  get 'challenge' => 'questions#challenge'
  get 'steal_piece' => 'questions#steal_piece'
  get 'assess_answer' => 'games#assess_answer'
  get 'random_game' => 'games#random_game'
  get 'resign_game' => 'games#resign'

  get 'sound_on' => 'users#sound_on'
  get 'sound_off' => 'users#sound_off'
  get 'hide_picture' => 'users#hide_picture'
  get 'show_picture' => 'users#show_picture'
  get 'hide_email' => 'users#hide_email'
  get 'show_email' => 'users#show_email'
  get 'hide_location' => 'users#hide_location'
  get 'show_location' => 'users#show_location'
  get 'hide_store' => 'users#hide_store'
  get 'show_store' => 'users#show_store'

  get 'coin_store' => 'games#coin_store'

  get 'express_checkout' => 'orders#express_checkout'
  get 'new_order' => 'orders#new'
  get 'orders' => 'orders#show'

  get 'leaderboard' => 'games#leaderboard'
  get 'process_wrong_answer' => 'games#process_wrong_answer'
  get 'end_attacker_steal_turn' => 'games#end_attacker_steal_turn'

  get '/users/:id', :to => 'users#update_profile', :as => :user
  post '/users/:id', :to => 'users#update_profile'

  post '/result' => 'questions#result'
  post '/chosen_category' => 'games#chosen_category'
  post '/spun_category' => 'games#spun_category'
  post 'steal_piece_settings' => 'games#steal_piece_settings'
  post '/pay' => 'questions#pay'

  root 'games#index'
end

app/models/question.rb
class Question < ActiveRecord::Base

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy, :accept_review]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
    random_wheel_spin = session[:spun_category]
    @game = Game.find(session[:current_game_id])
    if random_wheel_spin.eql? 'challenge'
      @game.user_meter = 3
      @game.save!
      redirect_to game_path(@game)
    else
      categoryQuestions = Question.where(:category => random_wheel_spin).where(:is_authorized => 't').order("RANDOM()")
      userDifficutly = 3;

      if((current_user.level / 10) + 1 < 20)
        userDifficutly = 2;
      end
      if((current_user.level / 10) + 1 < 10)
        userDifficutly = 1;
      end

      if(categoryQuestions.first.difficulty != userDifficutly)
        categoryQuestions = categoryQuestions.order("RANDOM()")
      end
      redirect_to categoryQuestions.first
    end
  end

  def challenge
    redirect_to Question.where(:category => session[:chosen_category]).order("RANDOM()").first
  end

  def steal_piece
    session[:is_in_steal] = true
    session[:steal_question_counter] = 0
    @game = Game.find(session[:current_game_id])
    @game.bet_piece = session[:bet_piece]
    @game.wanted_piece = session[:chosen_category]

    if !@game.steal_question_ids.eql? ''
      @game.is_second_steal_turn = true
      redirect_to Question.find(@game[:steal_question_ids].split[0].to_i)
    else
      categories = ['action', 'adventure', 'arcade', 'fps', 'racing', 'role-playing']
      rand_questions = ''
      categories.each do |category|
        rand_questions += Question.where(:category => category).where(:is_authorized => 't').sample.id.to_s + ' '
      end
      rand_questions.rstrip!

      @game.steal_question_ids = rand_questions
      @game.save!
      redirect_to Question.find(rand_questions.split[session[:steal_question_counter]])
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    if !session[:current_game_id].blank?
      @game = Game.find session[:current_game_id]
      if @game.user_turn_email != current_user.email
        redirect_to games_path
      end
      if session[:question_viewed] && @game.steal_question_ids.eql?('')
        redirect_to games_path
      else
        session[:question_viewed] = true
        if @game.is_second_steal_turn && @game.user_steal_correct < 0
          flash[:alert] = 'Your opponent is trying to steal your ' + @game.wanted_piece + ' piece. Defend yourself!'
        end
      end

      if session['steal_question_' + session[:steal_question_counter].to_s + '_viewed'] && @game.is_second_steal_turn == false
        redirect_to end_attacker_steal_turn_path
      elsif session['steal_question_' + session[:steal_question_counter].to_s + '_viewed'] && @game.is_second_steal_turn
        redirect_to process_wrong_answer_path
      end

      if !@game.steal_question_ids.eql? ''
        session['steal_question_' + session[:steal_question_counter].to_s + '_viewed'] = true
      end
    end

    @answer_choices = [@question.correct_answer, @question.incorrect_answer_1, @question.incorrect_answer_2, @question.incorrect_answer_3]
    @answer_choices.shuffle!
  end

  def accept_review
    @question.is_authorized = params[:is_accepted]
    if @question.is_authorized
      flash[:notice] = 'Question was successfully accepted.'
    else
      @question.destroy
      flash[:notice] = 'Question was successfully rejected.'
    end

    @question.save
    redirect_to show_review_path
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        @question.submitter = current_user.email
        if current_user.role == 'Admin' || current_user.role == 'Reviewer'
          @question.is_authorized = true
          @question.save
          format.html { redirect_to games_url, notice: 'Question was successfully submitted.' }
        elsif current_user.role == 'Player'
          @question.is_authorized = false
          @question.save
          format.html { redirect_to games_url, notice: 'Question was successfully submitted for review.' }
        end
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def show_review
    @questions = Question.where(:is_authorized => false)
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pay
    current_user.coins -= params[:amount].to_i
    current_user.save!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question_text, :correct_answer, :incorrect_answer_1, :incorrect_answer_2, :incorrect_answer_3, :category)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= simple_form_for(@question) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :question_text %>
    <%= f.input :correct_answer %>
    <%= f.input :incorrect_answer_1 %>
    <%= f.input :incorrect_answer_2 %>
    <%= f.input :incorrect_answer_3 %>
    <div class="form-group">
      <b>Category</b>
      <%= f.select(:category, options_for_select([['Role Playing','role-playing'],['Adventure','adventure'],['Racing','racing'], ['Arcade', 'arcade'], ['Action', 'action'], ['First person shooter', 'fps']]), {}, {class: "form-control"}) %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Question text</th>
      <th>Correct answer</th>
      <th>Incorrect answer 1</th>
      <th>Incorrect answer 2</th>
      <th>Incorrect answer 3</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.question_text %></td>
        <td><%= question.correct_answer %></td>
        <td><%= question.incorrect_answer_1 %></td>
        <td><%= question.incorrect_answer_2 %></td>
        <td><%= question.incorrect_answer_3 %></td>
        <td><%= question.category %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>Submit a new question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/pay.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

app/views/questions/result.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

app/views/questions/show.html.erb
<script>
    var currentCoins = <%= current_user.coins %>;
    <% if current_user.sound.nil? or current_user.sound %>
        playSound = true;
    <% end %>
    <% if !@game.nil? %>
        timerIntervalId = setInterval(updateTimer,10);
    <% end %>
</script>

<div class="container round-edges">
  <div class="row">
    <div class="text-center">
      <h2><%= @question.question_text %></h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-6">
    Submitter: <%= @question.submitter %>
    </br>
    <% submitter = User.find_by(email: @question.submitter) %>
    <% if !submitter.nil? %>
        <% if !submitter.location.blank? && !submitter.hide_location %>
            Location: <%= submitter.location %>
        <% end %>
    <% end %>
  </div>
  <div class="col-xs-6 text-right">Difficulty: <%= @question.difficulty / 10%>
    </br> Category: <%= @question.category %>
    </br>
    <% if !@game.nil? %>
        <% if !@game.steal_question_ids.eql? '' %>
            Correct: <%= @game.user_steal_correct.to_s %> / 6
        <% end %>
    <% end %>
  </div>
</div>

<div class="text-center">
  <div class="center-block">
    <div class="btn-group-vertical btn-group-lg" style="margin: 9px 0; width: 80%">

      <% @answer_choices.each do |answer_choice| %>
        <% if answer_choice.eql? @question.correct_answer %>
            <% if @question.is_authorized == false && (current_user.role == 'Admin' || current_user.role == 'Reviewer') %>
                <button type="button" class="btn btn-success correct">
                  <%= answer_choice %>
                </button>
            <% else %>
                <button type="button" class="btn btn-default correct">
                  <%= answer_choice %>
                </button>
            <% end %>
        <% else %>
              <button type="button" class="btn btn-default incorrect">
                <%= answer_choice %>
              </button>
        <% end %>
      <% end %>

    </div>
  </div>
</div>


    <% if @question.is_authorized == false && (current_user.role == 'Admin' || current_user.role == 'Reviewer') %>
        <div class="text-center">
          <%= button_to 'Accept question', accept_review_path, :class => 'btn btn-primary btn-lg', params: { id: params[:id], is_accepted: true }, :method => :get, :style => 'width: 80%' %>
        </div>
        <div class="text-center">
          <%= button_to 'Decline question', accept_review_path, :class => 'btn btn-primary btn-lg', params: { id: params[:id], is_accepted: false }, :method => :get, :style => 'width: 80%' %>
        </div>
    <% end %>


<% if !session[:current_game_id].blank? %>
    <div id="incorrectAnswerButton" class="text-center">
      <%= button_to 'Continue', assess_answer_path, params: { question_id: params[:id], answered_correctly: false }, :class => 'btn btn-info btn-lg btn-block', :method => :get %>
    </div>
    <div id="correctAnswerButton" class="text-center">
      <%= button_to 'Continue', assess_answer_path, params: { question_id: params[:id], answered_correctly: true }, :class => 'btn btn-info btn-lg btn-block', :method => :get %>
    </div>
<% end %>

<% if !@game.nil? %>
    <span id="countdown">
      00:30:00
    </span>
    <div id="coins">
      Coins: <%= current_user.coins %>
    </div>
    <div class="btn-group btn-group-justified" role="group" aria-label="...">
      <div class="btn-group" role="group">
        <button id="timeButton" type="button" class="btn btn-default" onclick='timerPowerUp();'>
          <img id="slowpoke" class='slowpoke' src='<%= image_url('slowpoke.png') %>' height="50">
          Slow-motion: 1 Gold
        </button>
      </div>
      <div class="btn-group" role="group">
        <button id="skipButton" type="button" class="btn btn-default" onclick='revealOnePowerUp();'>
          <img id="frog" class='frog' src='<%= image_url('bomb.png') %>' height="50">
          Kerboom!: 2 Gold
        </button>
      </div>
      <div class="btn-group" role="group">
        <button id="secondChanceButton" type="button" class="btn btn-default" onclick='secondChancePowerUp();'>
          <img id="fairy" class='fairy' src='<%= image_url('fairy.png') %>' width="50" height="50">
          Fairy in a Bottle: 3 Gold
        </button>
      </div>
    </div>
<% end %>

app/views/questions/show_review.html.erb
<h1>Pending Questions</h1>

<% if @questions.size > 0 %>
    <div class="panel panel-default">
      <table class="table table-striped table-hover">
        <thead>
        <th>
          Question
        </th>
        <th>
          Submitter
        </th>
        </thead>

        <tbody>
        <% @questions.each do |question| %>
            <tr class="info" onclick="location.href='<%= question_path(question) %>'">
              <td><%= question.question_text %></td>
              <td><%= question.submitter %></td>
              <td>
                  <div id="face-wrapper">
                      <% user = User.find_by(email: question.submitter) %>
                      <% if user.image %>
                          <img src='<%= user.image %>' class="img-circle face">
                      <% else %>
                          <img src='<%= image_url('default_profile.png')%>' class="img-circle face">
                      <% end %>
                  </div>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
<% end %>