config/routes.rb
Rails.application.routes.draw do
  resources :games do
    get :autocomplete_user_email, :on => :collection
  end
  resources :questions
  resources :games

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations'}

  get '/promote' => 'users#promote'
  post '/promote' => 'users#update'

  get 'show_review' => 'questions#show_review'
  get 'accept_review' => 'questions#accept_review'
  get 'show_game' => 'games#show'
  get 'challenge' => 'questions#challenge'
  get 'steal_piece' => 'questions#steal_piece'
  get 'assess_answer' => 'games#assess_answer'
  get 'random_game' => 'games#random_game'
  get 'resign_game' => 'games#resign'

  get 'sound_on' => 'users#sound_on'
  get 'sound_off' => 'users#sound_off'
  get 'hide_picture' => 'users#hide_picture'
  get 'show_picture' => 'users#show_picture'
  get 'hide_email' => 'users#hide_email'
  get 'show_email' => 'users#show_email'
  get 'hide_location' => 'users#hide_location'
  get 'show_location' => 'users#show_location'
  get 'hide_store' => 'users#hide_store'
  get 'show_store' => 'users#show_store'

  get 'coin_store' => 'games#coin_store'

  get 'express_checkout' => 'orders#express_checkout'
  get 'new_order' => 'orders#new'
  get 'orders' => 'orders#show'

  get 'leaderboard' => 'games#leaderboard'
  get 'process_wrong_answer' => 'games#process_wrong_answer'
  get 'end_attacker_steal_turn' => 'games#end_attacker_steal_turn'

  get '/users/:id', :to => 'users#update_profile', :as => :user
  post '/users/:id', :to => 'users#update_profile'

  post '/result' => 'questions#result'
  post '/chosen_category' => 'games#chosen_category'
  post '/spun_category' => 'games#spun_category'
  post 'steal_piece_settings' => 'games#steal_piece_settings'
  post '/pay' => 'questions#pay'

  root 'games#index'
end

app/models/game.rb
class Game < ActiveRecord::Base
  validates :opponent_user_email, presence: true, format: { with: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/}

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_filter :require_login
  autocomplete :user, :email

  def promote

  end

  # GET /games
  # GET /games.json
  def index
    @user = current_user # Needed for Merit

    if current_user.badges.size == 0
      award_badge(1)
    end

    if current_user.sign_in_count == 5
      award_badge(2)
    end

    if current_user.role.nil? || current_user.role.blank?
      current_user.role = 'Player'
      current_user.correct_answers_in_a_row = 0
      current_user.save
    end

    if Statistic.where(:email => current_user.email).blank?
      Statistic.create email: current_user.email, action_correct: 0, action_total: 0, adventure_correct: 0, adventure_total: 0, arcade_correct: 0, arcade_total: 0, fps_correct: 0, fps_total: 0, racing_correct: 0, racing_total: 0, role_playing_correct: 0, role_playing_total: 0, wins: 0, loses: 0
    end

    @opponent_turn_games = Game.where('user_email = ? OR opponent_user_email = ?', current_user.email, current_user.email).where.not(:user_turn_email => current_user.email).where(:is_game_over => false)
    @user_turn_games = Game.where(:user_turn_email => current_user.email).where(:is_game_over => false)
    @past_games = Game.where('user_email = ? OR opponent_user_email = ?', current_user.email, current_user.email).where(:is_game_over => true)
  end

  def spun_category
    session[:spun_category] = params[:spun_category]
    render js: "window.location = '#{questions_url}'"
  end

  def chosen_category
    session[:chosen_category] = params[:chosen_category]
    render js: "window.location = '#{challenge_url}'"
  end

  def steal_piece_settings
    session[:chosen_category] = params[:chosen_category]
    session[:bet_piece] = params[:bet_piece]
    render js: "window.location = '#{steal_piece_url}'"
  end

  def resign
    @game = Game.find session[:current_game_id]
    @user = current_user
    opponent = User.find_by(email: @game.opponent_user_email)
    opponent.coins += 5
    opponent.save!
    end_turn
    @game.is_game_over = true
    @game.save!
    redirect_to games_path
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @categories = ['action', 'adventure', 'arcade', 'fps', 'racing', 'role-playing']
    if @game.nil?
      @game = Game.find session[:current_game_id]
    end
    if session[:question_viewed] && @game.steal_question_ids.eql?('')
      session[:question_viewed] = false
      end_turn
      redirect_to games_path
    else
      @current_opponent = User.find_by email: @game.opponent_user_email
      @game.save!
      session[:current_game_id] = @game.id
      if !@game.steal_question_ids.eql? ''
        flash[:notice] = 'You opponent is trying to steal your ' + @game.bet_piece + ' piece. Answer more than ' + @game.opponent_steal_correct.to_s + ' question(s) correct to fend off the opponent.'
        redirect_to steal_piece_path
      end
      @won_games = Game.where(:user_email => current_user.email).where(:opponent_user_email => @current_opponent.email).where(:is_game_over => true)
      @lost_games = Game.where(:opponent_user_email => current_user.email).where(:user_email => @current_opponent.email).where(:is_game_over => true)
    end
  end

  def assess_answer
    @game = Game.find session[:current_game_id]
    @user = current_user
    @question = Question.find params[:question_id]
    session[:question_viewed] = false

    add_to_total_stat

    if !session[:steal_question_counter].blank?
      session[:steal_question_counter] += 1
    end

    if params[:answered_correctly] == "true"
      process_correct_answer
    else
      process_wrong_answer
    end

    set_question_difficulty
    @question.save!
  end

  def set_question_difficulty
    if (@question.difficulty > 39)
      @question.difficulty = 39
    elsif (@question.difficulty < 10)
      @question.difficulty = 10
    end
  end

  def process_correct_steal_turn
    @game.user_steal_correct += 1
    @game.save!

    if session[:steal_question_counter] == 6
      if @game.is_second_steal_turn
        if @game.user_steal_correct == @game.opponent_steal_correct
          process_tie_breaker
        elsif @game.user_steal_correct < @game.opponent_steal_correct
          give_piece_to_opponent @game.wanted_piece
        else
          award_piece @game.bet_piece
          remove_opponent_piece @game.bet_piece
          end_steal
          flash[:notice] = "Congrats! You stole the " + @game.bet_piece + " piece from your opponent."
          redirect_to game_path @game
        end
      else
        end_attacker_steal_turn
      end
    elsif session[:steal_question_counter] == 7
      remove_opponent_piece @game.bet_piece
      flash[:notice] = "Congrats! You sent your opponent's " + @game.bet_piece + " piece to the void!"
      end_steal
      redirect_to game_path @game
    else
      if @game.is_second_steal_turn && (@game.user_steal_correct > @game.opponent_steal_correct)
        flash[:notice] = 'Congrats, you successfully defended yourself and stole your opponents ' + @game.bet_piece + ' piece.'
        end_steal
        redirect_to game_path @game
      else
        redirect_to question_path @game.steal_question_ids.split[session[:steal_question_counter]]
      end
    end
  end

  def process_tie_breaker
    flash[:notice] = 'Tie breaker! Answer this correctly or else the opponent will steal your ' + @game.wanted_piece + ' piece.'
    @game.is_tie_breaker = true
    @game.save!
    redirect_to Question.where(:is_authorized => true).sample
  end

  def end_steal
    @game.is_second_steal_turn = false
    @game.bet_piece = ''
    @game.wanted_piece = ''
    @game.steal_question_ids = ''
    @game.is_tie_breaker = false
    @game.opponent_steal_correct = 0
    @game.user_steal_correct = 0
    @game.save!
    (0..session[:steal_question_counter].to_i).each do |i|
      session['steal_question_' + i.to_s + '_viewed'] = false
    end
    session[:steal_question_counter] = nil
  end

  def remove_piece category
    if category.eql? 'action'
      @game.user_pieces = @game.user_pieces.delete('1').strip
    elsif category.eql? 'adventure'
      @game.user_pieces = @game.user_pieces.delete('2').strip
    elsif category.eql? 'arcade'
      @game.user_pieces = @game.user_pieces.delete('3').strip
    elsif category.eql? 'fps'
      @game.user_pieces = @game.user_pieces.delete('4').strip
    elsif category.eql? 'racing'
      @game.user_pieces = @game.user_pieces.delete('5').strip
    elsif category.eql? 'role-playing'
      @game.user_pieces = @game.user_pieces.delete('6').strip
    end
    @game.save!
  end

  def remove_opponent_piece category
    if category.eql? 'action'
      @game.opponent_pieces = @game.opponent_pieces.delete('1').strip
    elsif category.eql? 'adventure'
      @game.opponent_pieces = @game.opponent_pieces.delete('2').strip
    elsif category.eql? 'arcade'
      @game.opponent_pieces = @game.opponent_pieces.delete('3').strip
    elsif category.eql? 'fps'
      @game.opponent_pieces = @game.opponent_pieces.delete('4').strip
    elsif category.eql? 'racing'
      @game.opponent_pieces = @game.opponent_pieces.delete('5').strip
    elsif category.eql? 'role-playing'
      @game.opponent_pieces = @game.opponent_pieces.delete('6').strip
    end
    @game.save!
  end

  def add_to_partial_stat
    statistic = Statistic.find_by email: @game.user_email
    if @question.category.eql? 'action'
      statistic.action_correct += 1
    elsif @question.category.eql? 'adventure'
      statistic.adventure_correct += 1
    elsif @question.category.eql? 'arcade'
      statistic.arcade_correct += 1
    elsif @question.category.eql? 'fps'
      statistic.fps_correct += 1
    elsif @question.category.eql? 'racing'
      statistic.racing_correct += 1
    elsif @question.category.eql? 'role-playing'
      statistic.role_playing_correct += 1
    end
    statistic.save!
  end

  def add_to_total_stat
    statistic = Statistic.find_by email: @game.user_email
    if @question.category.eql? 'action'
      statistic.action_total += 1
    elsif @question.category.eql? 'adventure'
      statistic.adventure_total += 1
    elsif @question.category.eql? 'arcade'
      statistic.arcade_total += 1
    elsif @question.category.eql? 'fps'
      statistic.fps_total += 1
    elsif @question.category.eql? 'racing'
      statistic.racing_total += 1
    elsif @question.category.eql? 'role-playing'
      statistic.role_playing_total += 1
    end
    statistic.save!
  end

  def end_turn
    session[:question_viewed] = false
    @game.round = @game.round + 1
    if(current_user.level > 0)
      current_user.level -= 1
    end

    if @game.user_meter == 3
      @game.user_meter = 0
    end
    current_user.correct_answers_in_a_row = 0
    if @game.user_email.eql? current_user.email
      @game.user_turn_email = @game.opponent_user_email
      @game.user_email,@game.opponent_user_email = @game.opponent_user_email,@game.user_email
      @game.user_pieces,@game.opponent_pieces = @game.opponent_pieces,@game.user_pieces
      @game.user_meter,@game.opponent_meter = @game.opponent_meter,@game.user_meter
      @game.user_steal_correct,@game.opponent_steal_correct = @game.opponent_steal_correct,@game.user_steal_correct
    end
    @game.save!
    current_user.save!
  end

  def award_piece category
    if category.eql? 'action'
      @game.user_pieces << ' 1'
    elsif category.eql? 'adventure'
      @game.user_pieces << ' 2'
    elsif category.eql? 'arcade'
      @game.user_pieces << ' 3'
    elsif category.eql? 'fps'
      @game.user_pieces << ' 4'
    elsif category.eql? 'racing'
      @game.user_pieces << ' 5'
    elsif category.eql? 'role-playing'
      @game.user_pieces << ' 6'
    end
    @game.user_pieces.lstrip!
    sorted_pieces = @game.user_pieces.split.sort
    @game.user_pieces = sorted_pieces.join(' ')
    if @game.user_pieces.eql? '1 2 3 4 5 6'
      @game.is_game_over = true

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_challenge_modal.html.erb
<div class="modal fade" id="challengeModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Earn a piece!</h4>
            </div>

            <div class="modal-body row">
                <div role="tabpanel">

                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#challenge" aria-controls="challenge" role="tab" data-toggle="tab">Challenge</a></li>
                        <li role="presentation">
                            <a href="#stealAPiece" aria-controls="stealAPiece" role="tab" data-toggle="tab">Steal a Piece</a></li>
                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content">

                        <div role="tabpanel" class="tab-pane active" id="challenge">
                            <div class="container col-md-12 text-center">
                                <div class="row">
                                    <% @categories.each_with_index do |category, i| %>
                                    <% if i == 3 %>
                                </div>
                                <div class="row">
                                    <% end %>
                                    <div class="col-md-3">
                                        <img id='<%= 'user' + category.capitalize + 'Image' %>' class='<%= 'user' + category.capitalize + 'Image' %>' src='<%= image_url('greyscale/'+ category + '.png') %>' width="50" height="50"></br>
                                        <%= category.capitalize %>
                                    </div>
                                    <% end %>
                                </div>
                            </div>
                        </div>

                        <div role="tabpanel" class="tab-pane" id="stealAPiece">
                            <div id="betChoiceTab" class="container col-md-12 text-center">
                                Piece to bet (Note: you cannot bet pieces your opponent already has)
                                <div class="row">
                                    <% @categories.each_with_index do |category, i| %>
                                    <% if i == 3 %>
                                </div>
                                <div class="row">
                                    <% end %>
                                    <div class="col-md-3">
                                        <img id='<%= 'userBet' + category.capitalize + 'Image' %>' class='<%= 'userBet' + category.capitalize + 'Image' %>' src='<%= image_url('greyscale/'+ category + '.png') %>' width="50" height="50"></br>
                                        <%= category.capitalize %>
                                    </div>
                                    <% end %>
                                </div>
                            </div>

                            <div id="stealChoiceTab" class="container col-md-12 text-center">
                                Piece to steal (Note: you cannot steal pieces you already have)
                                <div class="row">
                                    <% @categories.each_with_index do |category, i| %>
                                    <% if i == 3 %>
                                </div>
                                <div class="row">
                                    <% end %>
                                    <div class="col-md-3">
                                        <img id='<%= 'opponentSteal' + category.capitalize + 'Image' %>' class='<%= 'opponentSteal' + category.capitalize + 'Image' %>' src='<%= image_url('greyscale/'+ category + '.png') %>' width="50" height="50"></br>
                                        <%= category.capitalize %>
                                    </div>
                                    <% end %>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>
    <!-- /.modal-content -->
</div>
<!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
    $('#challengeModal').modal({
        backdrop: 'static',
        keyboard: false
    });
    $(window).load(function () {
        $('#challengeModal').modal('show')
    });
</script>

app/views/games/_form.html.erb
<%= simple_form_for(@game)  do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :opponent_user_email, :url => autocomplete_user_email_games_path, :as => :autocomplete %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-info btn-lg btn-block' %>
  </div>
<% end %>

<script>
    $(".autocomplete .required").toggleClass("string optional form-control");
    $("label").removeClass("string optional form-control")
</script>

app/views/games/_opponent_stats_modal.html.erb
<div class="modal fade" id="opponentStatsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <% if(@current_opponent.hide_email) %>
                <h4 class="modal-title" id="myModalLabel">Statistics and Achievements for Opponent</h4>
                <% else %>
                <h4 class="modal-title" id="myModalLabel">Statistics and Achievements for <%= @current_opponent.email %></h4>
                <% end %>

            </div>
            <div class="modal-body">
                <div role="tabpanel">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#oppstatistics" aria-controls="oppstatistics" role="tab" data-toggle="tab">Statistics</a></li>
                        <li role="presentation"><a href="#oppachievements" aria-controls="oppachievements" role="tab" data-toggle="tab">Achievements</a></li>
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="oppstatistics">
                            <table>
                                <tr>
                                    <% @categories.each_with_index do |category, i|  %>
                                    <% if i == 3 %>
                                </tr>
                                <tr>
                                    <% end %>
                                    <td>
                                        <img src='<%= image_url('icons/'+ category + '.png') %>' width="50" height="50">
                                        <% if category.eql? 'role-playing' %>
                                        <% category = category.split('-').join('_') %>
                                        <% end %>
                                        <% stat = Statistic.find_by email: @current_opponent.email %>
                                        <% if stat.send(category + '_total') == 0 %>
                                        -%
                                        <% else %>
                                        <%= (stat.send(category + '_correct') / stat.send(category + '_total')) * 100 %>%
                                        <% end %>
                                    </td>
                                    <% end %>
                                </tr>
                            </table>
                            Wins: <%= Statistic.find_by(email: @current_opponent.email).wins %> ||
                            Losses: <%= Statistic.find_by(email: @current_opponent.email).loses %>
                            <br>
                            Record against player:
                            <br>
                            Wins: <%= @won_games.size %> || Losses: <%= @lost_games.size %>
                            <br>
                            <% if !@current_opponent.location.blank? && !@current_opponent.hide_location %>
                            Location: <%= @current_opponent.location %>
                            <% end %>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="oppachievements">
                            <% @current_opponent.badges.each do |badge| %>
                            <div class="row">
                                <img src='<%= image_url('achievements/' + badge.id.to_s + '.png') %>' width="50px"><%= badge.name %> : <%= badge.description %>
                            </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

app/views/games/_piece_appearance_script.html.erb
<script>
    $("#stealChoiceTab").hide();
    var piece_to_bet = "";
    <% @categories.each_with_index do |category, i| %>
    <% if @game.user_pieces.split.include? (i + 1).to_s %>
    document.getElementById('user' + '<%= category.capitalize %>' + 'Image').src = '<%= image_url('icons/'+ category +'.png')%>';
    $('img.user' + '<%= category.capitalize %>' + 'Image').attr("src", '<%= image_url('icons/'+ category +'.png')%>');
    <% if !@game.opponent_pieces.split.include? (i + 1).to_s %>
    $('img.userBet' + '<%= category.capitalize %>' + 'Image').attr("src", '<%= image_url('icons/'+ category +'.png')%>');
    $(function () {
        $('img.userBet' + '<%= category.capitalize %>' + 'Image').click(function () {
            $(this).css('border', "solid 2px red");
            $("#betChoiceTab").hide();
            $("#stealChoiceTab").show();
            piece_to_bet = '<%= category %>';
        });
    });
    <% end %>
    <% else %>
    $('img.user' + '<%= category.capitalize %>' + 'Image').click(function () {
        $.post('/chosen_category', {chosen_category: '<%= category %>', type: 'challenge'});
    });
    <% end %>
    <% end %>

    <% @categories.each_with_index do |category, i| %>
    <% if @game.opponent_pieces.split.include? (i + 1).to_s %>
    document.getElementById('opponent' + '<%= category.capitalize %>' + 'Image').src = '<%= image_url('icons/'+ category + '.png')%>';
    $('img.opponent' + '<%= category.capitalize %>' + 'Image').attr("src", '<%= image_url('icons/'+ category + '.png')%>');
    <% if !@game.user_pieces.split.include? (i + 1).to_s %>
    $('img.opponentSteal' + '<%= category.capitalize %>' + 'Image').attr("src", '<%= image_url('icons/' + category + '.png')%>');
    $(function () {
        $('img.opponentSteal' + '<%= category.capitalize %>' + 'Image').click(function () {
            $.post('/steal_piece_settings', {
                chosen_category: '<%= category %>',
                bet_piece: piece_to_bet,
                type: 'steal'
            });
        });
    });
    <% end %>

    $('img.opponent' + '<%= category.capitalize %>' + 'Image').click(function () {
        $.post('/chosen_category', {chosen_category: '<%= category %>'});
    });
    <% end %>
    <% end %>

    wheelImageName = '<%= image_url('question_spinner.png') %>';
    begin();
    powerSelected(1);
</script>

app/views/games/_win_modal.html.erb
<% @game.is_game_over = true %>
<% @game.save! %>
<% @user = User.find_by(email: @game.user_email) %>
<% @user.coins += 5 %>
<% @user.save %>
<div class="modal fade" id="wonModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Congratulations! You've won!</h4>
      </div>
      <img id="youWin" src='<%= image_url('win.gif') %>'>
      You win 5 coins! Total coins: <%= @user.coins %>
      <%= button_to 'Back to game select', games_path, :class => 'btn btn-info btn-lg btn-block', :method => :get %>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
    $('#wonModal').modal({
        backdrop: 'static',
        keyboard: false
    });
    $(window).load(function () {
        $('#wonModal').modal('show')
    });
</script>

app/views/games/assess_answer.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

app/views/games/chosen_category.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<script>
    <% if current_user.sound.nil? or current_user.sound %>
    playSound = true;
    <% end %>
</script>

<div class="text-center">
  <p>
    <strong>Round:</strong>
    <%= @game.round %>
  </p>
</div>

<div class="container round-edges">
  <div class="row">
    <div class="col-xs-1">
      <div id="face-wrapper">
        <% if current_user.image && !current_user.hide_picture %>
            <%= link_to image_tag(current_user.image, :class => 'img-circle face'), '#', 'data-toggle' => 'modal', 'data-target' => '#statsModal' %>
        <% else %>
            <%= link_to image_tag("default_profile.png", :class => 'img-circle face'), '#', 'data-toggle' => 'modal', 'data-target' => '#statsModal' %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-5">
      <% if current_user.hide_email %>
          You - Level: <%= (current_user.level / 10) + 1 %>
      <% else %>
          <%= @game.user_email %> - Level: <%= (current_user.level / 10) + 1 %>
      <% end %>
      (Next level: <%= ((current_user.level % 10) - 10) * -1 %> exp)
      </br>

      <% @categories.each do |categories| %>
          <img id='<%= 'user' + categories.capitalize + 'Image' %>' src='<%= image_url('greyscale/'+ categories + '.png') %>' width="50" height="50">
      <% end %>
    </div>
    <div class="col-xs-5" style="border-left-style: dotted">
      <div class="pull-right">
        <% if @current_opponent.hide_email %>
            Opponent - Level: <%= (@current_opponent.level / 10) + 1 %>
        <% else %>
            <%= @game.opponent_user_email %> - Level: <%= (@current_opponent.level / 10) + 1 %>
        <% end %>
      </div>
      </br>
      <div class="pull-right">
        <% @categories.each do |categories| %>
            <img id='<%= 'opponent' + categories.capitalize + 'Image' %>' src='<%= image_url('greyscale/'+ categories + '.png') %>' width="50" height="50">
        <% end %>
      </div>
    </div>
    <div class="col-xs-1">
      <div class="pull-right">
        <div id="face-wrapper">
          <% if @current_opponent.image && !@current_opponent.hide_picture %>
              <%= link_to image_tag(@current_opponent.image, :class => 'img-circle face'), '#', 'data-toggle' => 'modal', 'data-target' => '#opponentStatsModal' %>
          <% else %>
              <%= link_to image_tag("default_profile.png", :class => 'img-circle face'), '#', 'data-toggle' => 'modal', 'data-target' => '#opponentStatsModal' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

</br>

<div class="arrow-down"></div>

<div class="row text-center" onClick="startSpin();">
  <canvas class="the_canvas" id="myDrawingCanvas" width="300" height="300">
    <p class="noCanvasMsg" align="center">Sorry, your browser doesn't support canvas.<br/>Please try another.</p>
  </canvas>
</div>


<div class="row text-center">
  <div class="col-xs-12">
    <img src='<%= image_url('triforce_meter/' + @game.user_meter.to_s + '.png') %>' width="150">
  </div>
  <div class="col-xs-4 buttonBox">
    <%= button_to 'Resign', resign_game_path, data: {confirm: 'Are you sure you want to resign?'}, :class => 'btn btn-info btn-block', :method => :get %>
  </div>
</div>

<% if @game.user_pieces == "1 2 3 4 5 6" %>
    <%= render 'games/win_modal' %>
<% end %>

<% if @game.user_meter == 3 %>
    <%= render 'games/challenge_modal' %>
<% end %>

<%= render 'games/piece_appearance_script' %>
<%= render 'games/opponent_stats_modal' %>

app/views/games/spun_category.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title></title>
</head>
<body>

</body>
</html>

app/views/games/steal_piece.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>